healthCheckTimeout: 320
logLevel: info
sendLoadingState: true
startPort: 10001
macros:
  scripts_dir: ${env.HOME}/scripts
  model_host: 0.0.0.0
models:
  glm4.7flash-general:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_glm4.7flash-general.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - glm4
    - glm4-general
  glm4.7flash-tools:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_glm4.7flash-tool-calling.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - glm4-tools
  nanbeige4.1-3b:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_nanbeige4.1-3b.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - nanbeige
  
  mirothinker:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_mirothinker.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 1800
    aliases:
    - mirothinker
  qwen3.6-27b-thinking:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.6-27b-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen27b-think
  qwen3.6-27b-thinking-mtp:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.6-27b-mtp-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen27b-think-mtp
  qwen3.6-35b-no-think:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.6-35b-non-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen3.6-35b-no-think
  qwen3.6-35b-thinking:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.6-35b-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen3.6-35b
  qwen3.5-122b-thinking:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.5-122b-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen122b-think
  qwen3.5-122b-no-think:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.5-122b-non-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen122b
  
  gemma4-31b:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_gemma4-31b.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - gemma4-31b
  
  qwen3-embedding:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3-embedding.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 100
    aliases:
    - qwen3-embedding
    
  lfm2.5-1b:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_LFM2_5_1b.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - lfm2.5
  lfm2.5-vl:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_LFM2_5_VL_1b.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - lfm-vision
  qwen3.5-4b-thinking:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.5-4b-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen4b-think
  qwen3.5-4b-no-think:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.5-4b-non-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen4b
  qwen3.5-9b-thinking:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.5-9b-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    useModelName: Qwen/Qwen3.5-9B
    aliases:
    - qwen9b-think
  qwen3.5-9b-no-think:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3.5-9b-non-thinking.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    useModelName: Qwen/Qwen3.5-9B
    aliases:
    - qwen9b
  qwen3-4b:
    proxy: http://${model_host}:${PORT}
    cmd: env MODEL_HOST=${model_host} MODEL_PORT=${PORT} bash ${scripts_dir}/start_qwen3_4b.sh
    env:
    - MODEL_PORT=${PORT}
    - MODEL_HOST=${model_host}
    ttl: 900
    aliases:
    - qwen3-4b-instruct
groups:
  qwen27b:
    swap: true
    exclusive: true
    members:
    - qwen3.6-27b-thinking
    - qwen3.6-27b-no-think
  qwen35b:
    swap: true
    exclusive: true
    members:
    - qwen3.6-35b-thinking
    - qwen3.6-35b-no-think
  qwen122b:
    swap: true
    exclusive: true
    members:
    - qwen3.5-122b-thinking
    - qwen3.5-122b-no-think
  qwen4b:
    swap: true
    exclusive: true
    members:
    - qwen3.5-4b-thinking
    - qwen3.5-4b-no-think
  qwen9b:
    swap: true
    exclusive: true
    members:
    - qwen3.5-9b-thinking
    - qwen3.5-9b-no-think
hooks:
  on_startup:
    preload: []
